name: Run Tests

on:
  push:
    paths:
      - 'example/*'
  pull_request:
    paths:
      - 'example/*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: make test
